### ISSUE TITLE
Reinforced Concrete Walls have no sprites

### ISSUE THREAD

**Issue by GrayRachnid** [Alanii/NewHestia#116]
#### Description of issue
Title

#### Difference between expected and actual behavior
Have a wall sprite

#### Steps to reproduce
Reinforce a concrete wall

#### Specific information for locating

![image](https://user-images.githubusercontent.com/6613514/96903435-d737ac80-1463-11eb-900d-5ff1b75a02ac.png)
![image](https://user-images.githubusercontent.com/6613514/96903447-dc94f700-1463-11eb-9b1b-96c5ce7f3dfd.png)

**Comment by io-util** [comment]
Properly fill out the issue like how you are supposed to be in the issue template, makes backtracking a lot easier and helps us.
