### ISSUE TITLE
Reinforced glass turns back into normal glass.

### ISSUE THREAD

**Issue by Kaksisilma** [Alanii/NewHestia#44]
#### Description of issue

When built into a strucutre, reinforced glass becomes normal glass. This also happens for borosil.

#### Difference between expected and actual behavior
Expected:
- Build window with reinforced glass
- Have a "Reinforced glass window" built.
Actual:
- Build a window with reinforced glass
- Have a "Glass window" built.

#### Steps to reproduce

- Grab reinforced glass sheets
- Build any structures out of it
- Cry

#### Length of time in which bug has been known to occur

Been an issue since the last hestia build tbh.

#### Client version, Server revision & Game ID

Server Revision: 2d7d99d475050284923c0c7acca13ee58a104223 - master - 2020-10-16
Game ID: b9E-cTOU

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this]

**Comment by BurpleBineapple** [comment]
Fixed a while ago, so closing this
