### ISSUE TITLE
Genemodder species cannot use voidsuits

### ISSUE THREAD

**Issue by Knightfall5** [Alanii/NewHestia#79]
#### Description of issue
The Genemodder species is unable to wear command voidsuits and most likely the other types as well. There is no option to refit voidsuits to this species either.

#### Steps to reproduce
Pick genemodder species, try to wear a command voidsuit, get a species cannot wear this error.

#### Client version, Server revision & Game ID

51e21135f6163921e930f0771277f68653fed730  b9G-cWEW

**Comment by io-util** [comment]
Refer to the template for properly creating Issues, especiallyy the "Bingo" section at the end We'll still look into it though.

**Comment by BurpleBineapple** [comment]
No idea if this was ever an issue in the first place, but it doesn't seem to be reproduceable now. Closing
